# Generated by Django 5.1.4 on 2025-04-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stack_remove_projects_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='github_repo_link',
            field=models.CharField(default='https://github.com/tethcode', max_length=500),
        ),
        migrations.AddField(
            model_name='stack',
            name='live_link',
            field=models.CharField(default='https://x.com/tethcode', max_length=500),
        ),
    ]
