# Generated by Django 5.1.4 on 2025-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stack_github_repo_link_stack_live_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='github_repo_link',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='live_link',
        ),
        migrations.AddField(
            model_name='projects',
            name='github_repo_link',
            field=models.CharField(default='https://github.com/tethcode', max_length=500),
        ),
        migrations.AddField(
            model_name='projects',
            name='live_link',
            field=models.CharField(default='https://x.com/tethcode', max_length=500),
        ),
    ]
